---
abstract: 'construct prereq parameters of Module::Build from cpanfile'
author:
  - 'Toshio Ito <toshioito@cpan.org>'
build_requires:
  Test::More: '0'
configure_requires:
  Module::Build: '0.42'
dynamic_config: 1
generated_by: 'Module::Build version 0.4205, CPAN::Meta::Converter version 2.141170'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Module-Build-Prereqs-FromCPANfile
no_index:
  directory:
    - t
    - xt
    - eg
    - inc
  file:
    - README.pod
recommends:
  Module::Build: '0.4004'
requires:
  CPAN::Meta::Prereqs: '2.132830'
  Exporter: '0'
  Module::CPANfile: '1.0000'
  version: '0.80'
resources:
  bugtracker: https://github.com/debug-ito/Module-Build-Prereqs-FromCPANfile/issues
  repository: git://github.com/debug-ito/Module-Build-Prereqs-FromCPANfile.git
version: '0.02'
